apiVersion: v1
data:
  .dockerconfigjson: hAU8hb1hUNb7uSXwYdYeWTFBoRXG4ZB+Vsrfli7KCELsbFqqG9tbFW+X9rWnApSUQ9P5CUYFRCp/YXSE2SBwdbq9IocPeLU59eFKQSSYdhato4PfEBZg+e9u6AwIzDf2x9TYcA7lEnt1A0xYH09/tLf9Jb9209VZdChwA5aW51P2haSqkMk9WboIJkP0XtilBNy07Du81x+dEINZjOAmdJbRBwJrWPhNPNFeF8coblf+lICYBEnzOHovJqB7XA9n.eQ8y8W1wr0RceR1J.0pS39KJ3rF9rBqM1xH8IGw==
kind: Secret
metadata:
  creationTimestamp: null
  name: docker-auth
  namespace: dev
type: kubernetes.io/dockerconfigjson
# kubesec:v:3
# kubesec:gcp:projects/clouddevtest/locations/global/keyRings/db-keyring/cryptoKeys/kubesec-key:CiQAjqHU4Ec2PyDX5yM0r/juwP9WCPVwPf967F0+a6+9C6ExmzgSSQBfiTrmaNGPdwuZBKaYu8ftrUIb4MXmn2A5xcafc29P8p9GxW1SoVmKWg3orvdOvA+Tcf4UHTfQc75eKBnlDmnoNdZN8LtMgKA=
# kubesec:mac:J7hkt9rtCAzi8qPB.dcI0+WpPNnisoXUQWDCnQQ==
