apiVersion: v1
data:
  .dockerconfigjson: 9K4C4somcixTFM4098c3MX2fh+9JC6KCpGYLaTNKw3a6fDzxdRisbNMQ23t0PaSEnpr1P0TURzCgnjCs/11TCuT3hUVDJgMLqeb6yCcvnpWWwlrFvpAr6AJry3Ulf4xpucLpLv/wKgpLWCYu7LP1IogsWCPkr5L2U203hUp88AF534SG7LbE2sU5teR6RS94kE9nP9KbluDKgN3awmASpeHI8oBolSRmvTdkSf4dHN/KbkfD4d5fBJ2vTJJkprIA.6ldnpWPNCBgiE9bg.h8/uh/h1D6hUkVzqINokAA==
kind: Secret
metadata:
  creationTimestamp: null
  name: docker-auth
  namespace: dev
type: kubernetes.io/dockerconfigjson
# kubesec:v:3
# kubesec:gcp:projects/clouddevtest/locations/global/keyRings/db-keyring/cryptoKeys/kubesec-key:CiQAjqHU4HJJQHPpnaP28k9TvHo3VL0YqkoXSV1OyBmxr5loilQSSQBfiTrm1v1YvdjZV1Sgekbf9n+ZTB3BzmkT0+zTPAESg7kExAJtXmtt6ZJ/qxQeI7tLG++6i/tcd46dw8DZW0vsYRCvwO58OYE=
# kubesec:mac:5YopfV4/FK6soz8h.78+L6c94gDsZVdCQNgLsEw==
