apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.app.label }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.app.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.app.label }}
    spec:
      containers:
        - name: {{ .Values.deployment.app.label }}
          image: {{ .Values.deployment.app.image.name }}:{{ .Values.deployment.app.image.tag }}
          ports:
            - containerPort: {{ .Values.deployment.app.port }}
      imagePullSecrets:
        - name: {{ .Values.secret.docker.name }}