apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: skaffold-sample
  template:
    metadata:
      labels:
        app: skaffold-sample
    spec:
      containers:
        - name: nginx-container
          image: ponz1652/cicd_test:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080