apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    password: AgCQAL+biCScod2rY57kCfz/mmMfxKeAoNEXPeXlUH1TVAcecgjbeVGQ6vp3gs50N0Xjqt0jlPbsYOUXem2EE1CsaOG1N4ImDM/XN7cQ7a2BK0SLEO6ryBKTujhSZ2A7wYaXyVk01mmIh8t7Oky2fsNQ7u0AP2wg47cNRonspydXAacpVBLFy5kkqkrb4VTU9vIefX9mxQvNo8BLBCMVdtaJKW4kTEo/tfyi+3HVQAgUeh8fvWvTs4l/ucV7e7ifaL3SwZEZx4ihXhm9rIoovDUFATnFY7xXvmR8ZK3oGVuuc6wZAw3B0LX4LAp5NVSloPhgLg6Uwr74CVpovD7Tfno/FlqRBNxw8tuNEsCFCGa8uNwHPnVDfbgkL/L0b8Nqe+jej3VjSTkERxdt8uXT5FXuZzsMJjYjAc/b0Oh7lZIlus6bUE4oYOcVIKTSrx2gH32jgXxPkYEpVjOCYMgB4jm5orL2Lj/xGANxi+kUdkSAq/R36nGcXYCwRuYW5p8QEq5N2mO24ITjxbDymLrkpaVqivYDBRJ8x+PE0yD0tLs/Yp+77W40IcSta2geSpj6xNZffb9QI9gU3GSYXc2L6BMS//7ANMFVxqjJMj6tF0oiRYEffuCyZgze2oE8++TK0AnExVbpSu0bv4LDbId/8plczNRCb7DFFf8xMalJVoNa+A+RMb6XU/dyS6YeUJ4D6IYbje0d6A==
    username: AgATFc1VlWWE1cB8THi8Tjz77BrymLK8XvkWnpoyBoVYP3HrBCLutjBA4s/qVm+6/0HKph9gmADxxWMuUrZmbuiREIyoOEsF0eNAUycWKPe93EHzUz3LKl5XJNOqoAGUiLVJsubTw2wJVbj6kSbG1DkUrbqiCXqxnBOM5rjQ10L6y0QdhRGdkTNjfiQP4joO8sXWq8S1tVz3ZVq/BqxuyckrCRvny9JloZTKkcBZIaQWzvM4iipXT5RoGp8PCZVy88gbzM3TdHC9XQgWZZbhLy2T9o64oQQ+QBc4iOQ5EdoC7v3P3wcBKEI6ipdENimGuAqcfJJkgD+EpBzAZrkxChBvs2tRkvJVg6MkQvXu/uEmOYNYRCmxyYF7nUXgmp1H/ijaI0Qbnl0yWYfEuQ23qAuzhV3HpfnEGruwrvi1ImpmttLpeHjzP09R4p/HYan2SiM3Y/nimWix4ycfGZrPJ+PFDOzx4ZJ4fv+uMN1ODvJVfXQLRxY3Y81wJczXSCF13kjjy5BR9XuOkUijQeKD1dL8/C0ZdeG8BAJ5jzODtii9ZOu0fax8N97VuWfscoRQ7Entm7AWJOlIYpu9JHeCC5fyjvNmyWFDw1nPyoMI1gfN4VNzAmU72qHV2SYsJYx02dBMBOX1fbzh5f996ZjjFwubmI2j3oyeGPTx996SOTsvNSAlRyWuOEL+uNdQqVtkLVkhFl5x
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Values.secret.name }}
      namespace: {{ .Values.namespace }}
    type: Opaque
status: {}

