apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.app.port }}
  selector:
    app: {{ .Values.deployment.app.label }}