version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.3
    working_directory: /go/src/github.com/project/cicd_test
    steps:
      - setup_remote_docker:
          version: 17.11.0-ce
      - checkout
      - run:
          name: Install helm
          command: |
            curl -O https://get.helm.sh/helm-v2.14.1-linux-amd64.tar.gz
            tar -zxvf helm-v2.14.1-linux-amd64.tar.gz
            sudo mv linux-amd64/helm /usr/local/bin/helm
      - run:
          name: Add helm repo list
          command: |
            helm init -c
            helm repo add cicd_test_chart https://ponsukeee.github.io/cicd_test_chart/stable
      - run:
          name: Download config repo
          command: |
            git clone https://github.com/Ponsukeee/cicd_test_config
            git config --global user.email "test@example.com"
            git config --global user.name "test"
      - run:
          name: Create manifest with helm
          command: |
            helm fetch cicd_test_chart/helloworld
            helm template helloworld-${CHART_VERSION}.tgz --set deployment.app.image.tag=latest > cicd_test_config/helloworld/manifest.yaml
      - run:
          name: Push config repo
          command: |
            cd cicd_test_config
            git add -A
            git commit -m "circleci"
            git push https://github.com/Ponsukeee/cicd_test_config master

            

      