version: 2.1
executors:
  default:
    working_directory: /go/src/github.com/project/gke_test
    docker:
      - image: circleci/golang:1.11
commands:
  build:
    steps:
      - run:
          name: Build
          command: |
            docker build -t ${OWNER}/${CIRCLE_PROJECT_REPONAME}:latest -f ./dev/Dockerfile .
            docker tag ${OWNER}/${CIRCLE_PROJECT_REPONAME}:latest ${OWNER}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}
  push_image:
    steps:
      - run:
          name: Push image to registory
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker push ${OWNER}/${CIRCLE_PROJECT_REPONAME}
  manifest_update:
    steps:
      - run:
          name: Install helm
          command: |
            curl -O https://get.helm.sh/helm-v2.14.1-linux-amd64.tar.gz
            tar -zxvf helm-v2.14.1-linux-amd64.tar.gz
            sudo mv linux-amd64/helm /usr/local/bin/helm
      - run:
          name: Add helm repo list
          command: |
            helm init -c
            helm repo add cicd_test_chart https://ponsukeee.github.io/cicd_test_chart/stable
      - run:
          name: Download config repo
          command: |
            git clone https://github.com/Ponsukeee/cicd_test_config
            git config --global user.email "test@example.com"
            git config --global user.name "test"
      - run:
          name: Create manifest with helm
          command: |
            helm fetch cicd_test_chart/chatter
            helm template chatter-${CHART_VERSION}.tgz --set app.container.tag=latest > cicd_test_config/helloworld/manifest.yaml
      - run:
          name: Push config repo
          command: |
            cd cicd_test_config
            git add -A
            git commit -m "circleci"
            git push https://github.com/Ponsukeee/cicd_test_config master
jobs:
  build:
#     executor:
#       name: default
#     steps:
#       - setup_remote_docker:
#           version: 17.11.0-ce
# #      - run:
# #          command: |
# #            sudo chown root /usr/bin/docker
# #            sudo chmod u+s /usr/bin/docker
#       - checkout
#       - build
#       - push_image
  manifest_update:
    executor:
      name: default
    steps:
      - checkout
      - manifest_update
workflows:
  build_and_update:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - manifest_update:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/