---
# Source: chatter/templates/app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
        - name: goapp
          image: ponz1652/chatter:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-auth
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-auth
                  key: pass
      imagePullSecrets:
        - name: docker-auth
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: prod
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 80
      targetPort: 8080
  selector:
    app: goapp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: prod
data:
  PORT: "8080"
  DBMS: "mysql"
  DB_HOST: "db"
  DB_PORT: "3306"
  DB_NAME: "chatter"
---
# Source: chatter/templates/db.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-auth
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-auth
                  key: pass
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-auth
                  key: rootPass

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: prod
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: db
