# Default values for helloworld.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: prod

app:
  label: goapp
  replicaCount: 3
  container:
    image: ponz1652/chatter
    tag: latest
    port: 8080
  service:
    name: app-service
    type: LoadBalancer
    port: 80
  configMap:
    name: app-config
    dbms: mysql
    database: chatter
  secret:
    name: docker-auth
  env:
    user: DB_USER
    pass: DB_PASS

db:
  label: db
  replicaCount: 3
  container:
    image: mysql
    tag: latest
    port: 3306
  service:
    name: db-service
    port: 3306
  # configMap:
  #   name: db-config
  #   database: chatter
  secret:
    name: db-auth
    user: user
    pass: pass
    rootPass: rootPass
  env:
    user: MYSQL_USER
    pass: MYSQL_PASSWORD
    rootPass: MYSQL_ROOT_PASSWORD
    database: MYSQL_DATABASE

# deployment:
#   app:
#     label: goapp
#     replicaCount: 3
#     port: 8080
#     image:
#       name: ponz1652/chatter
#       tag: latest
#   db:
#     label: mysql
#     replicaCount: 1
#     port: 3306
#     image:
#       name: mysql
#       tag: latest

# service:
#   name: app-service
#   type: LoadBalancer
#   port: 80

# env:
#   app:
#     db:
#       username: DB_USER
#       pass: DB_PASS
#   db:
#     username: MYSQL_USERNAME
#     pass: MYSQL_PASSWORD
#     rootPass: MYSQL_ROOT_PASSWORD

# configmap:
#   app:
#     name: app-config
#     db:
#       dbname: chatter

# secret:
#   db:
#     name: db-auth
#     key:
#       username: username
#       pass: password
#       rootPass: rootPassword
#   docker:
#     name: docker-auth
